version: '3.7'

services: 
  todo-api:
    build: 
      context: ./services/todo-api
      dockerfile: Dockerfile.stage
    command: gunicorn --bind 0.0.0.0:5000 manage:app
    volumes:
      - ./services/todo-api/:/usr/src/todo-api/
    ports: 
      - 5000:5000
    env_file: 
      - ./services/todo-api/.env.stage
    depends_on: 
      - database
  todo-spa:
    build: 
      context: ./services/todo-spa
      dockerfile: Dockerfile.stage
    volumes:
      - static_volume:/usr/src/todo-spa/
    expose: 
      - 8080
  database:
    image: postgres:12-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment: 
      - POSTGRES_USER=${TODO_DATABASE_USER_STAGE}
      - POSTGRES_PASSWORD=${TODO_DATABASE_PASSWORD_STAGE}
      - POSTGRES_DB=${TODO_DATABASE_NAME_STAGE}
  nginx: 
    build: 
      context: ./services/nginx
      dockerfile: Dockerfile.stage
    volumes:
      - static_volume:/usr/src/todo-spa/
    ports:
      - 80:80
    depends_on: 
      - todo-api
      - todo-spa
  
volumes:
  postgres_data:
  static_volume: