version: '3.7'

services: 
  todo-api:
    build: ./services/todo-api
    command: python manage.py run -h 0.0.0.0
    volumes:
      - ./services/todo-api/:/usr/src/todo-api/
    ports: 
      - 5000:5000
    env_file: 
      - ./services/todo-api/.env.dev
    depends_on: 
      - database
  todo-spa:
    build: ./services/todo-spa
    volumes:
      - './services/todo-spa:/usr/src/todo-spa'
      - '/usr/src/todo-spa/node_modules'
    expose: 
      - 8080
  database:
    image: postgres:12-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment: 
      - POSTGRES_USER=${TODO_DATABASE_URL_DEV}
      - POSTGRES_PASSWORD=${TODO_DATABASE_PASSWORD_DEV}
      - POSTGRES_DB=${TODO_DATABASE_NAME_DEV}
    ports:
      - 5432:5432
  nginx: 
    build: 
      context: ./services/nginx
      dockerfile: Dockerfile.dev
    ports:
      - 1337:80
    depends_on: 
      - todo-api
      - todo-spa
  
volumes:
  postgres_data: