version: '3.7'

services: 
  api:
    build: ./services/todo-api
    command: python app.py run -h 0.0.0.0
    volumes:
      - ./services/todo-api/:/usr/src/todo-api/
    ports:
      - 5000:5000
    env_file: 
      - ./services/todo-api/.env.dev